[project]
name = "ouriprata"
version = "0.1.0"
description = ""
authors = [{ name = "23Edu4rd0", email = "eduardo.vchaves23@gmail.com" }]
requires-python = ">=3.14,<4.0"

dependencies = [
    "django (>=6.0.7,<7.0.0)",
    "django-jazzmin (>=3.0.5,<4.0.0)",
    "django-tailwind (>=4.5.0,<5.0.0)",
    "django-browser-reload (>=1.21.0,<2.0.0)",
    "django-colorfield (>=0.14.0,<1.0.0)",
    "gunicorn (>=23.0.0,<24.0.0)",
    "whitenoise (>=6.9.0,<7.0.0)",
    "dj-database-url (>=3.0.1,<4.0.0)",
    "psycopg2-binary (>=2.9.10,<3.0.0)",
    "pillow (>=11.3.0,<12.0.0)",
    "python-dotenv (>=1.1.1,<2.0.0)",
]


[tool.uv]
package = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = ["taskipy (>=1.14.1,<2.0.0)", "ruff (>=0.15.20,<0.16.0)"]

[tool.taskipy.tasks]
run = 'python manage.py runserver'
migrate = 'python manage.py migrate'
migrations = 'python manage.py makemigrations'
test = 'python manage.py test'

prod = 'DJANGO_ENV=production python manage.py collectstatic --noinput && DJANGO_ENV=production SECURE_SSL_REDIRECT=False gunicorn config.wsgi:application --bind 0.0.0.0:8000'
check = 'DJANGO_ENV=production python manage.py check --deploy'

style = 'python manage.py tailwind start'
build = 'python manage.py tailwind build'

lint = 'ruff lint .'
format = 'ruff format .'
pos_format = 'ruff check . --fix'

[tool.ruff]
line-length = 79
extend-exclude = ['migrations']


[tool.ruff.lint]
preview = true
select = ['I', 'F', 'E', 'W', 'PL', 'PT']

[tool.ruff.format]
preview = true
quote-style = 'single'
