# Generated by Django 5.2.3 on 2025-06-24 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MenuItems",
            new_name="Menu_Items",
        ),
    ]
