# Generated by Django 5.2.3 on 2025-06-24 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0002_rename_menuitems_menu_items"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categories",
            options={"verbose_name": "Categoria", "verbose_name_plural": "Categorias"},
        ),
        migrations.AlterModelOptions(
            name="menu_items",
            options={
                "verbose_name": "Item do Menu",
                "verbose_name_plural": "Itens do Menu",
            },
        ),
    ]
