# Generated by Django 6.0.7 on 2026-07-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('feminino', 'Feminino'), ('masculino', 'Masculino'), ('unissex', 'Unissex')], max_length=20),
        ),
    ]
