# Generated by Django 5.2.3 on 2025-06-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0003_alter_categories_options_alter_menu_items_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menu_items",
            options={"verbose_name": "Produto", "verbose_name_plural": "Produtos"},
        ),
    ]
