# Generated by Django 6.0.7 on 2026-07-31 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_add_variants_collections_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_season',
            field=models.BooleanField(default=False, help_text='Exibe as peças desta coleção em destaque na página inicial. Se marcar mais de uma, vale a primeira em ordem alfabética.', verbose_name='Coleção da estação'),
        ),
        migrations.AddField(
            model_name='collection',
            name='season_label',
            field=models.CharField(blank=True, help_text='Ex: "Coleção de Inverno". Se vazio, usa "Coleção da estação".', max_length=60, verbose_name='Rótulo da estação'),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deixe em branco se a peça não está em promoção. Precisa ser menor que o preço normal.', max_digits=10, null=True, verbose_name='Preço promocional'),
        ),
    ]
