# Generated by Django 5.2.3 on 2025-07-11 16:53

from django.db import migrations


def add_joais(apps, schema_editor):
    Joais = apps.get_model('catalogo', 'Joais')
    Material = apps.get_model('catalogo', 'Material')
    Ocasiao = apps.get_model('catalogo', 'Ocasiao')
    material_obj, _ = Material.objects.get_or_create(material='Ouro 14k')
    ocasiao_obj, _ = Ocasiao.objects.get_or_create(ocasiao='Formatura')
    Joais.objects.get_or_create(
        nome='Anel com Pedra Safira',
        descricao='Anel elegante com pedra safira azul, ideal para ocasiões especiais, como formaturas',
        preco=299.99,
        imagem='joias/anel_safira.png',
        material=material_obj,
        ocasiao=ocasiao_obj,
        destaque=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_joais_ocasiao'),
    ]

    operations = [
        migrations.RunPython(add_joais)
    ]
