# Generated by Django 5.2.3 on 2025-07-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_rename_fields_material_ocasiao'),
    ]

    operations = [
        migrations.AddField(
            model_name='joais',
            name='em_promocao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joais',
            name='preco_promocional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
