# Generated by Django 5.2.3 on 2025-07-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_joais_em_promocao_joais_preco_promocional'),
    ]

    operations = [
        migrations.AddField(
            model_name='joais',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
