# Generated by Django 5.2.3 on 2025-07-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_joais_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
    ]
