# Generated by Django 5.2.3 on 2025-07-16 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_categorias_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joais',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.categorias'),
        ),
    ]
