# Generated by Django 5.2.3 on 2025-07-23 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_populate_categorias_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joais',
            options={},
        ),
        migrations.AlterField(
            model_name='joais',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem principal', null=True, upload_to='catalogo'),
        ),
        migrations.CreateModel(
            name='JoaisImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='catalogo/extra')),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição')),
                ('joia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_extra', to='catalogo.joais')),
            ],
            options={
                'verbose_name': 'Joia',
                'verbose_name_plural': 'Joias',
            },
        ),
    ]
