# Generated by Django 5.2.3 on 2025-07-23 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0016_alter_joais_options_alter_joais_imagem_joaisimagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joaisimagem',
            options={'ordering': ['ordem'], 'verbose_name': 'Imagem da Joia', 'verbose_name_plural': 'Imagens da Joia'},
        ),
    ]
