# Generated by Django 5.2.4 on 2025-07-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0018_pedido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
