# Generated by Django 5.2.4 on 2025-07-26 14:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0019_delete_pedido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 - Muito Ruim'), (2, '2 - Ruim'), (3, '3 - Regular'), (4, '4 - Bom'), (5, '5 - Excelente')], help_text='Avaliação de 1 a 5 estrelas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('titulo', models.CharField(blank=True, help_text='Título opcional da avaliação', max_length=100)),
                ('comentario', models.TextField(help_text='Comentário detalhado sobre o produto')),
                ('foto', models.ImageField(blank=True, help_text='Foto do cliente usando o produto (opcional)', null=True, upload_to='reviews/')),
                ('recomendado', models.BooleanField(default=True, help_text='Recomenda este produto?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('aprovado', models.BooleanField(default=False, help_text='Avaliação aprovada pela moderação')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalogo.joais')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-data_criacao'],
                'unique_together': {('produto', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='reviews/imagens/')),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='catalogo.review')),
            ],
            options={
                'verbose_name': 'Imagem da Avaliação',
                'verbose_name_plural': 'Imagens das Avaliações',
            },
        ),
    ]
