"""
Django settings for food_site project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from dotenv import load_dotenv
from pathlib import Path

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.getenv(
    'SECRET_KEY',
)

# SECURITY WARNING: don't run with debug turned on in production!

# Padrão é False: se a variável não for definida no servidor, o site sobe
# seguro. Ligar o debug em produção expõe código-fonte, SQL e configurações
# na tela de erro.
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes')

# Em produção vem de ALLOWED_HOSTS (domínios separados por vírgula). O Railway
# expõe o domínio gerado em RAILWAY_PUBLIC_DOMAIN.
ALLOWED_HOSTS = [
    h.strip() for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h.strip()
]

_railway_domain = os.getenv('RAILWAY_PUBLIC_DOMAIN', '').strip()
if _railway_domain:
    ALLOWED_HOSTS.append(_railway_domain)

if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']

# Application definition

INSTALLED_APPS = [
    'catalogo.apps.CatalogoConfig',
    'accounts.apps.AccountsConfig',
    'theme',
    'jazzmin',
    'tailwind',
    'django_browser_reload',
    'colorfield',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

INTERNAL_IPS = [
    '127.0.0.1',
]

TAILWIND_APP_NAME = 'theme'

JAZZMIN_SETTINGS = {
    'theme': 'cyborg',
    'site_title': 'Administração do OuriPrata',
    'site_header': 'OuriPrata Admin',
    'welcome_sign': 'Bem-vindo ao Painel do OuriPrata',
    'copyright': 'OuriPrata © 2025',
    'show_sidebar': True,
    'navigation_expanded': True,
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Ferramenta de desenvolvimento: injeta um script de auto-reload em cada
# página. Não deve rodar em produção.
#
# Entra depois do SecurityMiddleware, que o Django recomenda manter no topo:
# assim os cabeçalhos e redirecionamentos de segurança valem para todas as
# respostas e o ambiente de desenvolvimento não mascara problemas de ordem.
if DEBUG:
    MIDDLEWARE.insert(
        MIDDLEWARE.index('django.middleware.security.SecurityMiddleware') + 1,
        'django_browser_reload.middleware.BrowserReloadMiddleware',
    )

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Em produção o Railway injeta DATABASE_URL ao ligar o Postgres ao serviço.
# Sem a variável, cai no SQLite local para desenvolvimento.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

_database_url = os.getenv('DATABASE_URL', '').strip()
if _database_url:
    import dj_database_url

    DATABASES['default'] = dj_database_url.parse(
        _database_url,
        conn_max_age=600,
        conn_health_checks=True,
    )

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True

# Media files
#
# MEDIA_ROOT precisa apontar para o volume persistente do Railway, senão as
# fotos enviadas pelo admin somem no próximo deploy (o disco do container é
# descartável).

MEDIA_URL = '/media/'
MEDIA_ROOT = os.getenv('MEDIA_ROOT', os.path.join(BASE_DIR, 'media'))

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# STATICFILES_STORAGE foi removido no Django 5.1 e estava sendo ignorado em
# silêncio: o whitenoise nunca chegou a atuar. A forma atual é STORAGES.
#
# A variante Manifest põe um hash no nome de cada arquivo (styles.a1b2c3.css),
# então uma versão nova nunca é servida do cache antigo do navegador. Isso
# importa para segurança: sem hash, quem já visitou o site continuaria com o
# JavaScript anterior mesmo depois de uma correção.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'profile'
LOGOUT_REDIRECT_URL = 'home'

CSRF_TRUSTED_ORIGINS = [
    'http://localhost',
    'http://127.0.0.1',
]

# Domínios extras via variável (separados por vírgula), mais o domínio que o
# Railway gera para o serviço.
CSRF_TRUSTED_ORIGINS += [
    o.strip()
    for o in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',')
    if o.strip()
]

if _railway_domain:
    CSRF_TRUSTED_ORIGINS.append(f'https://{_railway_domain}')


# --- Segurança em produção -------------------------------------------------
# Só entram fora do DEBUG: com SSL redirect ativo, o servidor de
# desenvolvimento em http entraria em laço de redirecionamento.

if not DEBUG:
    # O Railway termina o TLS no roteador dele e repassa a requisição em http.
    # Sem este cabeçalho o Django acharia que a conexão é insegura e redirecionaria
    # em laço infinito.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HSTS instrui o navegador a só acessar por https. Começa em 1 hora de
    # propósito: se algo der errado com o certificado, o prejuízo expira rápido.
    # Suba para 31536000 (1 ano) depois de confirmar que o domínio está estável.
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '3600'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = False

    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
