# Generated by Django 5.2.4 on 2025-07-24 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('catalogo', '0019_delete_pedido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cart',
            name='ring_size',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Tamanho do Anel'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'produto', 'ring_size')},
        ),
    ]
